# Generated by Django 3.0.10 on 2021-03-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='faculty_code',
            field=models.CharField(default='CODE', max_length=100),
        ),
    ]
