# Generated by Django 3.0.10 on 2021-03-18 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210319_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table1',
            old_name='acad_year1',
            new_name='academic_year1',
        ),
        migrations.RenameField(
            model_name='year',
            old_name='acad_year',
            new_name='academic_year',
        ),
    ]
