# Generated by Django 3.0.10 on 2021-03-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20210319_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table2',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='table2',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='table2',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='table2',
            name='start_time',
        ),
        migrations.AddField(
            model_name='table2',
            name='time',
            field=models.CharField(choices=[('08.30 TO 09.30', '08.30 TO 09.30'), ('09.30 TO 10.30', '09.30 TO 10.30'), ('10.30 TO 11.30', '10.30 TO 11.30'), ('11.30 TO 12.30', '11.30 TO 12.30'), ('12.30 TO 01.30', '12.30 TO 01.30'), ('01.30 TO 02.30', '01.30 TO 02.30'), ('02.30 TO 03.30', '02.30 TO 03.30'), ('03.30 TO 04.30', '03.30 TO 04.30'), ('04.30 TO 05.30', '04.30 TO 05.30')], default='1st', max_length=100, null=True),
        ),
    ]
