# Generated by Django 3.0.10 on 2021-03-19 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20210319_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table2',
            name='paper_name',
        ),
        migrations.AddField(
            model_name='table2',
            name='paper_name1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.paper'),
        ),
    ]
