# Generated by Django 3.0.10 on 2021-03-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20210319_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='part1',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='sem1',
        ),
    ]
