# Generated by Django 3.0.10 on 2021-03-21 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20210319_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='off_day',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='duration',
        ),
    ]
