# Generated by Django 3.0.10 on 2021-03-21 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20210321_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table2',
            name='faculty_name',
        ),
        migrations.AddField(
            model_name='table2',
            name='faculty_name1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fac1', to='webapp.faculty'),
        ),
        migrations.AddField(
            model_name='table2',
            name='faculty_name2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fac2', to='webapp.faculty'),
        ),
        migrations.AddField(
            model_name='table2',
            name='faculty_name3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fac3', to='webapp.faculty'),
        ),
        migrations.AddField(
            model_name='table2',
            name='faculty_name4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fac4', to='webapp.faculty'),
        ),
    ]
