# Generated by Django 3.0.10 on 2021-03-21 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20210321_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table1',
            name='sem1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.sem'),
        ),
    ]
