# Generated by Django 3.0.10 on 2021-03-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20210322_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='table2',
            name='paper_code1',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AlterField(
            model_name='table2',
            name='paper_name1',
            field=models.CharField(default='name', max_length=200),
        ),
    ]
