# Generated by Django 3.0.10 on 2021-03-22 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20210322_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table2',
            name='Lecture_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Lecture'),
        ),
        migrations.AlterField(
            model_name='table2',
            name='choose',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.table1'),
        ),
        migrations.AlterField(
            model_name='table2',
            name='day',
            field=models.CharField(blank=True, choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], default='MONDAY', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='table2',
            name='paper_code1',
            field=models.CharField(blank=True, default='name', max_length=200),
        ),
        migrations.AlterField(
            model_name='table2',
            name='paper_name1',
            field=models.CharField(blank=True, default='name', max_length=200),
        ),
        migrations.AlterField(
            model_name='table2',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.room_no'),
        ),
        migrations.AlterField(
            model_name='table2',
            name='section_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.section'),
        ),
        migrations.AlterField(
            model_name='table2',
            name='time',
            field=models.CharField(blank=True, choices=[('08.30 TO 09.30', '08.30 TO 09.30'), ('09.30 TO 10.30', '09.30 TO 10.30'), ('10.30 TO 11.30', '10.30 TO 11.30'), ('11.30 TO 12.30', '11.30 TO 12.30'), ('12.30 TO 01.30', '12.30 TO 01.30'), ('01.30 TO 02.30', '01.30 TO 02.30'), ('02.30 TO 03.30', '02.30 TO 03.30'), ('03.30 TO 04.30', '03.30 TO 04.30'), ('04.30 TO 05.30', '04.30 TO 05.30')], default='1st', max_length=100, null=True),
        ),
    ]
