# Generated by Django 3.0.10 on 2021-03-22 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20210322_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='table2',
            name='room1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rom2', to='webapp.room_no'),
        ),
        migrations.AlterField(
            model_name='table2',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rom1', to='webapp.room_no'),
        ),
    ]
