# Generated by Django 3.0.10 on 2021-03-22 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20210322_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table2',
            name='faculty_name2',
        ),
        migrations.RemoveField(
            model_name='table2',
            name='faculty_name3',
        ),
        migrations.RemoveField(
            model_name='table2',
            name='faculty_name4',
        ),
        migrations.RemoveField(
            model_name='table2',
            name='room',
        ),
        migrations.AlterField(
            model_name='table2',
            name='room1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rom1', to='webapp.room_no'),
        ),
    ]
