# Generated by Django 3.0.10 on 2021-03-22 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20210322_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='table2',
            name='faculty_name2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fac2', to='webapp.faculty'),
        ),
    ]
