# Generated by Django 3.0.10 on 2021-03-24 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_auto_20210324_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='Lecture_type',
            field=models.CharField(default='TH', max_length=100, verbose_name='Lecture code'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='Lecture_type_ff',
            field=models.CharField(default='Theory', max_length=100, verbose_name='Lecture Name'),
        ),
        migrations.AlterField(
            model_name='sem',
            name='semester',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th')], default='1st', max_length=100, null=True, verbose_name='Choose Semester'),
        ),
        migrations.AlterField(
            model_name='sem',
            name='show1',
            field=models.BooleanField(verbose_name='Tick which you want to show to students'),
        ),
        migrations.AlterField(
            model_name='table1',
            name='academic_year1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.year', verbose_name='Select Academic Year'),
        ),
        migrations.AlterField(
            model_name='table1',
            name='course_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Course', verbose_name='Choose Course'),
        ),
        migrations.AlterField(
            model_name='table1',
            name='part1',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th')], default='1st', max_length=100, null=True, verbose_name='Part'),
        ),
        migrations.AlterField(
            model_name='table1',
            name='sem1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.sem', verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='table2',
            name='Lecture_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Lecture', verbose_name='Lecture Type'),
        ),
        migrations.AlterField(
            model_name='table2',
            name='choose',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.table1', verbose_name='Choose faculty1'),
        ),
        migrations.AlterField(
            model_name='table2',
            name='day',
            field=models.CharField(blank=True, choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=100, null=True, verbose_name='Choose day'),
        ),
        migrations.AlterField(
            model_name='table2',
            name='faculty_name1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fac1', to='webapp.faculty', verbose_name='Choose faculty1'),
        ),
        migrations.AlterField(
            model_name='table2',
            name='faculty_name2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fac2', to='webapp.faculty', verbose_name='Choose faculty2(for lab)'),
        ),
        migrations.AlterField(
            model_name='table2',
            name='paper_code1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Enter paper code'),
        ),
        migrations.AlterField(
            model_name='table2',
            name='paper_name1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Enter paper name'),
        ),
        migrations.AlterField(
            model_name='table2',
            name='section_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.section', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='table2',
            name='time',
            field=models.CharField(blank=True, choices=[('08.30 TO 09.30', '08.30 TO 09.30'), ('09.30 TO 10.30', '09.30 TO 10.30'), ('10.30 TO 11.30', '10.30 TO 11.30'), ('11.30 TO 12.30', '11.30 TO 12.30'), ('12.30 TO 01.30', '12.30 TO 01.30'), ('01.30 TO 02.30', '01.30 TO 02.30'), ('02.30 TO 03.30', '02.30 TO 03.30'), ('03.30 TO 04.30', '03.30 TO 04.30'), ('04.30 TO 05.30', '04.30 TO 05.30')], max_length=100, null=True, verbose_name='Choose time'),
        ),
        migrations.AlterField(
            model_name='year',
            name='academic_year',
            field=models.CharField(default='2019-20', max_length=100, verbose_name='Academic Year'),
        ),
        migrations.AlterField(
            model_name='year',
            name='show',
            field=models.BooleanField(verbose_name='Tick which you want to show to students'),
        ),
    ]
