# Generated by Django 3.0.10 on 2021-03-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_auto_20210324_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table2',
            name='day',
            field=models.CharField(blank=True, choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday')], max_length=100, null=True, verbose_name='Choose day'),
        ),
    ]
