# Generated by Django 3.0.10 on 2021-03-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_auto_20210325_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='sem_fac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester2', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th')], default='1st', max_length=100, null=True, verbose_name='Choose Semester')),
                ('show12', models.BooleanField(verbose_name='Tick which you want to show to students')),
            ],
        ),
    ]
