# Generated by Django 3.0.10 on 2021-03-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_sem_fac'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='username', max_length=200)),
                ('password', models.CharField(default='Password', max_length=200)),
            ],
        ),
    ]
