# Generated by Django 3.0.10 on 2021-03-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table2',
            name='time',
            field=models.CharField(blank=True, choices=[('08.30TO09.30', '08.30 TO 09.30'), ('09.30TO10.30', '09.30 TO 10.30'), ('10.30TO11.30', '10.30 TO 11.30'), ('11.30TO12.30', '11.30 TO 12.30'), ('12.30TO01.30', '12.30 TO 01.30'), ('01.30TO02.30', '01.30 TO 02.30'), ('02.30TO03.30', '02.30 TO 03.30'), ('03.30TO04.30', '03.30 TO 04.30'), ('04.30TO05.30', '04.30 TO 05.30')], max_length=100, null=True, verbose_name='Choose time'),
        ),
    ]
