# Generated by Django 3.0.10 on 2021-03-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_auto_20210328_0112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='User_data',
        ),
        migrations.AlterField(
            model_name='sem',
            name='show1',
            field=models.BooleanField(verbose_name='Tick if this is the current going semester'),
        ),
        migrations.AlterField(
            model_name='year',
            name='show',
            field=models.BooleanField(verbose_name='Tick if this is the current year'),
        ),
    ]
